version: "3.8"

services:
  mysql_db:
    container_name: blind-local-db
    image: mysql:8.0
    restart: unless-stopped
    volumes:
      - mysql_db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=blind
      - MYSQL_USER=blind
      - MYSQL_PASSWORD=blind
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    container_name: blind-local-redis
    image: redis:7-alpine
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  mysql_db:
  redis_data:
